/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as BudgetPaymentRouteImport } from './routes/budget-payment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetPaymentRoute = BudgetPaymentRouteImport.update({
  id: '/budget-payment',
  path: '/budget-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget-payment': typeof BudgetPaymentRoute
  '/collections': typeof CollectionsRoute
  '/contracts': typeof ContractsRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/kanban': typeof KanbanRoute
  '/overview': typeof OverviewRoute
  '/payments': typeof PaymentsRoute
  '/risks': typeof RisksRoute
  '/schedule': typeof ScheduleRoute
  '/vendors': typeof VendorsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget-payment': typeof BudgetPaymentRoute
  '/collections': typeof CollectionsRoute
  '/contracts': typeof ContractsRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/kanban': typeof KanbanRoute
  '/overview': typeof OverviewRoute
  '/payments': typeof PaymentsRoute
  '/risks': typeof RisksRoute
  '/schedule': typeof ScheduleRoute
  '/vendors': typeof VendorsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget-payment': typeof BudgetPaymentRoute
  '/collections': typeof CollectionsRoute
  '/contracts': typeof ContractsRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/kanban': typeof KanbanRoute
  '/overview': typeof OverviewRoute
  '/payments': typeof PaymentsRoute
  '/risks': typeof RisksRoute
  '/schedule': typeof ScheduleRoute
  '/vendors': typeof VendorsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget-payment'
    | '/collections'
    | '/contracts'
    | '/inbox'
    | '/insights'
    | '/kanban'
    | '/overview'
    | '/payments'
    | '/risks'
    | '/schedule'
    | '/vendors'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget-payment'
    | '/collections'
    | '/contracts'
    | '/inbox'
    | '/insights'
    | '/kanban'
    | '/overview'
    | '/payments'
    | '/risks'
    | '/schedule'
    | '/vendors'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/budget-payment'
    | '/collections'
    | '/contracts'
    | '/inbox'
    | '/insights'
    | '/kanban'
    | '/overview'
    | '/payments'
    | '/risks'
    | '/schedule'
    | '/vendors'
    | '/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetPaymentRoute: typeof BudgetPaymentRoute
  CollectionsRoute: typeof CollectionsRoute
  ContractsRoute: typeof ContractsRoute
  InboxRoute: typeof InboxRoute
  InsightsRoute: typeof InsightsRoute
  KanbanRoute: typeof KanbanRoute
  OverviewRoute: typeof OverviewRoute
  PaymentsRoute: typeof PaymentsRoute
  RisksRoute: typeof RisksRoute
  ScheduleRoute: typeof ScheduleRoute
  VendorsRoute: typeof VendorsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-payment': {
      id: '/budget-payment'
      path: '/budget-payment'
      fullPath: '/budget-payment'
      preLoaderRoute: typeof BudgetPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetPaymentRoute: BudgetPaymentRoute,
  CollectionsRoute: CollectionsRoute,
  ContractsRoute: ContractsRoute,
  InboxRoute: InboxRoute,
  InsightsRoute: InsightsRoute,
  KanbanRoute: KanbanRoute,
  OverviewRoute: OverviewRoute,
  PaymentsRoute: PaymentsRoute,
  RisksRoute: RisksRoute,
  ScheduleRoute: ScheduleRoute,
  VendorsRoute: VendorsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
